language: python

python:
  - "2.6"
  - "2.7"
  - "3.2"

before_script:
  - cp konekta/test_settings.py.example konekta/local_settings.py
  - psql -c 'create database konekta_test;' -U postgres
  - psql -d konekta_test -c "UPDATE pg_database SET datistemplate=true WHERE datname='konekta_test'" -U postgres
  - psql -d konekta_test -f /usr/share/postgresql/9.1/contrib/postgis-1.5/postgis.sql -U postgres
  - psql -d konekta_test -f /usr/share/postgresql/9.1/contrib/postgis-1.5/spatial_ref_sys.sql -U postgres
  - psql -d konekta_test -f /usr/share/postgresql/9.1/contrib/postgis-1.5/postgis_comments.sql -U postgres

install: "pip install -r requirements.txt --use-mirrors"

script:
  - "python ./manage.py test"

#notifications:
#  irc:
#    channels: "irc.freenode.org#konekta"
#    on_success: change
#    on_failure: change